name = input("Enter your Name :")
age = int(input("Enter your Age :"))
city = input("enter your city : ")
course = input("Enter your course :")
print("==========================")
print("     Personal profile     ")
print("==========================")
print("Name   :",name)
print("Age    :",age)
print("City   :",city)
print("Course :",course)
print("==========================")